server:
  servlet:
    context-path: /app-a
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/a_database
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      console:
        enabled: true
